### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by astrojuanlu** [ebabio/restrictedCircular3BodyProblem#1]
Hi! Arrived here from https://twitter.com/ebabiofe/status/1381269490990780420, thanks a lot for sharing this code!

However, the fact that it doesn't have a license prevents me from effectively reusing it. Under the Bern convention, the default is "all rights reserved".

Would you please https://choosealicense.com/ ?

And, if I may suggest one, https://choosealicense.com/licenses/mit/ is permissive, which means that it's commercial-friendly, simple to understand, and can be remixed with a large amount of software. It doesn't force derivative works (translations, rewrites, applications depending on it) to be released as open source though, so if this is something you would like to enforce, a GPL-like license might be closer to what you want.

**Comment by ebabio** [comment]
Sure, I had never bothered about that. Added an mit license. Feel free to use it!
